### PR TITLE
Armoring IRI in < and > to make them distinguishable from CURIEs

### PR DESCRIPTION
**Pull request by retog**

### CODE REVIEW

**Comment by retog** [comment]
closing for now. Pending adapting tests and parsing site.

**Comment by rubensworks** [comment]
Thanks for this PR, but I'm afraid I can't accept it in this state.
This library aims to be compatible with the old N3.js triple format, which would be broken by this PR.

CURIEs are not in-scope for this library. A new/other library may be better suited for this.

**Comment by retog** [comment]
Hi Ruben, it's your choice, but I can't really understand why you prioritize compatibility with (the bugs of) the old N3.js higher than compatibility with current Turtle and Sparql standards. The PR doesn't introduce CURIES just makes sure that URIs aren't mistaken for CURIES, e.g. by Sparql.

**Comment by rubensworks** [comment]
It's not really a matter of prioritization, but simply the fact that this library's main purpose is to offer a translation layer to/from the old N3.js format. N3.js's old format is still used in quite a few places (including some of my own libraries). So in that respect, it doesn't make much sense to break this functionality.

Nevertheless, I understand the value of your PR, it's just not suited for this library here. I may be open to passing config options to enable this functionality though.

**Comment by retog** [comment]
Ok, sure. Thanks for the explanation.

A little detail: https://github.com/rubensworks/rdf-string.js/blob/master/lib/TermUtil.ts#L10 has the example '"3"^^xsd:number' which the library would never produce unless "xsd:number" is wrongly used as datatype of the literal.

**Comment by rubensworks** [comment]
> A little detail: https://github.com/rubensworks/rdf-string.js/blob/master/lib/TermUtil.ts#L10 has the example '"3"^^xsd:number' which the library would never produce unless "xsd:number" is wrongly used as datatype of the literal.

Yes, that looks wrong indeed, thanks for letting me know.

**Comment by rubensworks** [comment]
FYI, I just also had a need for this, so I've created a [fork of this package](https://github.com/rubensworks/rdf-string-ttl), and merged your PR there.

**Pull request closed without merging**
